### ISSUE TITLE
Feature request: Smoothing out lat,lng points 

### ISSUE THREAD

**Issue by martinschnurer** [brenzy/gpx-smoother#4]
GPS went crazy and it jumped a little bit, if I could smooth out also lat,lng coordinates of the points, it would be great!

![image](https://github.com/brenzy/gpx-smoother/assets/14320432/93d64d31-55ed-4625-93b9-751ed876db8c)

**Comment by brenzy** [comment]
Hi @martinschnurer.  The distance of these jumps in location are so small, that it would be very difficult to programatically figure out which ones are the "jumps" and which ones are actually on the route.  If it's only a few points, you could use a route editor to slide the points back into place, or just delete them.
